### ISSUE TITLE
Index name conflict

### ISSUE THREAD

**Issue by mtanasiewicz** [intaro/custom-index-bundle#15]
When working with entities that have same class names and same index names defined, the indexes arent created for all the entities. It looks like there is some internal map by name or by Entity+name.

Example. Lets say you are working with a modular monolith application, and You have 2 Entites named `Address` in different modules. They have separate table names with module prefix, like `module1_address` and `module_2_address`. Both Address entities have `street` property. If we want to create index on `street` property in both tables using same annotaion like:
```
@Index(
 *      name="street_idx",
 *      columns={"street"}
 *  ),
 */
```
there will be index for only one entity created. I don't know if this is a bug, missing feature or some db limitation, but I thought it is worth mentioning.

Thanks for the good work!

**Comment by muxx** [comment]
Hi! The annotation `@Index` is Doctrine standard annotation. This bundle provides own annotation `@CustomIndex` for the index creation.

**Comment by mtanasiewicz** [comment]
@muxx Well of course I am referring CustomIndex annotation here, not the Doctrine one. I have just copied my namespace alias here ;) I think this issue was closed too soon, because it still exists.

**Comment by muxx** [comment]
You're right, such map is [here](https://github.com/intaro/custom-index-bundle/blob/master/Command/IndexUpdateCommand.php#L137).

But i'm not sure that we should make the indexes unique within bundle or module. Indexes are unique within database in PostgreSQL. 

In our practice we don't define `name` attribute in annotation and this bundle generates unique names for indexes.

**Comment by mtanasiewicz** [comment]
It is really weird, because when I specify name attribute, I actually get index with my custom name and this bundle prefix. For example, index created for `street_idx` results in index name `i_cindex_street_idx` created in database. 

It is really useful to have an option to create a name for an index, just to keep things in order and improve readability. Simply looking only at database schema, and reading index names, can give you really valuable information at what indexes are created and what they refer to. IMHO Passing index name should be completely disabled, or fixed to properly handle indexes with same names across system. Otherwise if You dont know how it works under the hood, you can loose quite some time, figuring out why some indexes are created and some are'nt. That was my case.

**Comment by muxx** [comment]
I understand you. But changing of the name convention can break production state of the indexes after bundle updating. We'll add explanation about name prefix in README.
