### ISSUE TITLE
Issue with updating schema

### ISSUE THREAD

**Issue by ScreamZ** [intaro/custom-index-bundle#4]
Hello,

first I want to thank you for the good job, this was exactly what I was looking for but...

How are you handling the case that standard `doctrine:schema:update` will detect the created index as non-schema-compliant and will dispatch an action to remove this index ?

Best regards

**Comment by muxx** [comment]
Hi! Thanks for your feedback 👍 

When we use this bundle in symfony project we don't use command `doctrine:schema:update`. Optimally to use `doctrine/migrations` with this bundle.

**Comment by ScreamZ** [comment]
Thanks for the answer, the idea is dumping the SQL commands and add it to the `public function up(Schema $schema)` in the migration file ? This is it ?

Regards

**Comment by muxx** [comment]
Not quite so. When we run deploying two commands are executed:

```
app/console doctrine:mi:mi
app/console intaro:doctrine:index:update
```

First command applies the changes of doctrine schema. Second command applies the changes of custom indexes.

**Comment by ScreamZ** [comment]
Okay,

just have to take care that index are not removed by the first one.

Thanks for all,

have a nice day :)
