### ISSUE TITLE
Symfony 4 support

### ISSUE THREAD

**Issue by AlexanderMatveev** [intaro/custom-index-bundle#7]
:+1:

**Comment by kiler129** [comment]
@muxx @teohhanhui Isn't that a simple `composer.json` change?

**Comment by muxx** [comment]
Yes, exactly. We are going to add it but will be glad if you'll make PR yourself )

**Comment by kiler129** [comment]
We’re currently testing it. I will make PR after making sure everything works with 4.2 with fixes (hopefully just the version constrain ;)).

**Comment by muxx** [comment]
👍

**Comment by kiler129** [comment]
@muxx PR ready: https://github.com/intaro/custom-index-bundle/pull/9

I will be glad if you can review & merge + tag version ;)

**Comment by kiler129** [comment]
@muxx @teohhanhui We will really like to not use a private fork. Is there anything I can do to make the PR reviewable?

**Comment by AlexanderMatveev** [comment]
Update a composer package too please: https://packagist.org/packages/intaro/custom-index-bundle

**Comment by muxx** [comment]
Done!
